# p6spy query logging via slf4j logger 'p6spy'
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=elapsed=%(executionTime)ms | category=%(category) | connection=%(connectionId) | sql=%(sqlSingleLine)
excludecategories=debug,result,resultset,batch
