{
 "title": "APIs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "total QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, uri) (\n    rate(http_server_requests_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "error rate top 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5,\n  (\n    sum by (uri) (rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))\n  /\n    sum by (uri) (rate(http_server_requests_seconds_count[5m]))\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri) (\n  rate(http_server_requests_seconds_count[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (uri) (\n  rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])\n)\n/\nsum by (uri) (\n  rate(http_server_requests_seconds_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}