{
 "title": "JVM/Runtime",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "http_server_requests_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "process_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jvm_memory_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}